version: '3.4'


services:
#    connectionPoint.Gateway:
#        image: connectionpoint.gateway
#        build:
#            context: .
#            dockerfile: src/ConnectionPoint.Gateway/Dockerfile
#        ports:
#        - "5083:80"
#        depends_on:
#        - postgres
#        - redis
    postgres:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: postgres
            POSTGRES_DB: connectionPoint
        ports:
        - "5432:5432"
        volumes:
        - postgres:/var/lib/postgresql/data
    redis:
        image: redis:alpine
        ports:
        - "6379:6379"
        volumes:
        - redis:/data
    
volumes:
    postgres:
    redis: