version: '3.4'

services:
    connectionPoint.Gateway:
        image: connectionpoint.gateway
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - ASPNETCORE_URLS=https://+;http://+
            - ASPNETCORE_HTTPS_PORT=7000
            - ASPNETCORE_Kestrel__Certificates__Default__Password=password
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/connectionpoint.pfx
            - ASPNETCORE_ENVIRONMENT=Development
        ports:
            - "5000:80"
            - "7000:443"
        depends_on:
            - postgres
            - redis
        networks:
            - connectionPointNetwork
        volumes:
            - ${HOME}/.aspnet/https:/https
    postgres:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: postgres
            POSTGRES_DB: connectionPoint
        ports:
            - "5432:5432"
        volumes:
            - postgres:/var/lib/postgresql/data
        networks:
            - connectionPointNetwork
    redis:
        image: redis:alpine
        ports:
            - "6380:6379"
        volumes:
            - redis:/data
        networks:
            - connectionPointNetwork

volumes:
    postgres:
    redis:
networks:
    connectionPointNetwork:
        driver: bridge